version: "3"
# Names our volume
# volumes:
#   data:
services:
  db:
    container_name: mysql_pitu
    image: mysql:5.7
    # restart: 'always'
    hostname: mysql
    # <Port exposed> : < MySQL Port running inside container>
    ports:
      - "3306:3306"
    # Where our data will be persisted
    # volumes:
    #   - ./data:/var/lib/mysql
    environment:
      # Password for root access
      - MYSQL_ROOT_PASSWORD=123456
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=pitu_db
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=pitu_db
      # - MYSQL_HOST=localhost
      
    expose:
    # Opens port 3306 on the container
      - '3306'

  nodejs:
    container_name: node_pitu
    build: . # caminho do Dockerfile
    command: npm run start
    environment:
      - TOKEN_SECRET=a752221c36afcfbe10aaee831d4a2d9f
      - TOKEN_EXPIRIES=3600
      - DBAAS_MYSQL_ENDPOINT=mysql://root:123456@172.18.0.1:3306/pitu_db
      - DBAAS_MYSQL_HOSTS=172.18.0.1
      - DBAAS_MYSQL_PASSWORD=123456
      - DBAAS_MYSQL_PORT=3306
      - DBAAS_MYSQL_USER=root
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/app
    depends_on:
      - db

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
